### ISSUE TITLE
Add note to setup about WSL for Windows users

### ISSUE THREAD

**Issue by nventuro** [OpenZeppelin/docs.openzeppelin.com#119]
In the [setting-up](https://docs.openzeppelin.com/learn/setting-up-a-node-project) Learn guide, we should add a notice about [Windows Subsystem for Linux (WSL)](https://docs.microsoft.com/en-us/windows/wsl/install-win10) for Windows users.

**Comment by frangio** [comment]
Closing this since there are users successfully using our tools on Windows, and we intend to fix the issues that come up, so using WSL is not strictly necessary.
