### ISSUE TITLE
Add search

### ISSUE THREAD

**Issue by abcoathup** [OpenZeppelin/docs.openzeppelin.com#15]
https://docs.openzeppelin.com doesn't currently have search, it would be great to have this functionality.  

The old ZeppelinOS documentation website has search https://docs.zeppelinos.org/versions
(There were issues with this search where the results were not clear on which version the results applied to, so community members could end up using old versions and get confused).

**Comment by abcoathup** [comment]
There is a Pull Request https://github.com/OpenZeppelin/docs.openzeppelin.com/pull/8 to add search (Algolia DocSearch)

**Comment by abcoathup** [comment]
Based on feedback by PaulRBerg on the community Telegram.

**Comment by frangio** [comment]
Algolia DocSearcg is already set up and I have started work on integrating it in #8. I think the main thing pending is fixing the CSS so that it looks good. 

We should also test how it works afterwards.

**Comment by spalladino** [comment]
Make sure that search properly handles multiple versions (see https://github.com/OpenZeppelin/openzeppelin-sdk/issues/922)
