### ISSUE TITLE
Licensing / use of content?

### ISSUE THREAD

**Issue by samajammin** [OpenZeppelin/docs.openzeppelin.com#155]
Hey folks! Terrific work on these docs. I'm particularly a fan of the [learning resources](https://docs.openzeppelin.com/learn/) you created.

I don't see a license on this repo. Looking at your [TOS](https://openzeppelin.com/tos/), it looks like the content is under copyright - is that correct? I'm wondering if any of this content could be used on ethereum.org (e.g. adding some of your [dapp content](https://docs.openzeppelin.com/learn/building-a-dapp) to our [dapp page](https://ethereum.org/dapps/). Would that be something you'd be ok with? We'd be happy to give you credit where we make any use of your work. I could also share any PRs for you folks to review before publishing any changes.

Please let me know. Thanks!

**Comment by abcoathup** [comment]
Hi @samajammin,

Thanks for the interest in the OpenZeppelin documentation.  We think the Learn guides are pretty awesome too.

You are welcome to link to the OpenZeppelin documentation.
For anything more than linking, I will need to come back to you in a week or two.

**Comment by samajammin** [comment]
Thanks, @abcoathup. Yes, in addition to linking to your documentation, we're interested in incorporating your content onto ethereum.org. The overwhelming feedback we've gotten from the community is that in addition to linking out to resources, they'd like to see more content directly on the site.

To give you an example of what I'm envisioning, I'm thinking of adding an introductory paragraph on the [dapp page](https://ethereum.org/dapps/) modeled after the first paragraph on your ["building a dapp" page](https://docs.openzeppelin.com/learn/building-a-dapp):

> Decentralized Applications (dapps) are web applications backed by Ethereum smart contracts. Instead of using a centralized server or database, these applications rely on the blockchain as a storage backend. This leads to potentially unstoppable applications: anyone can spin up a copy of the frontend, and freely connect it to the public Ethereum network.

As mentioned, we'd cite OpenZeppelin as a reference whenever using your content.

Please get back to me when possible. Thanks again!

**Comment by spalladino** [comment]
Hey @samajammin! Apologies for the delay in the response. We'd be happy (and honored!) to have bits of our content in ethereum.org, as long as the original source in `docs.openzeppelin.com` is linked to, as you say. In case you want to copy an entire guide (instead of parts of it) verbatim into ethereum.org, we'd ask for the [canonical tag](https://moz.com/learn/seo/canonicalization) to be set as well.

We still need to do more work around choosing an appropriate license for this repo, but in interest of time, would this written response here in Github suffice for you? I can also shoot you an email with the same text (as Github responses are editable) if it helps.

**Comment by samajammin** [comment]
@spalladino @abcoathup - please take a look at the PR I referenced above & let me know if that citation format is adequate. You can view the preview deploy of the page here:
https://deploy-preview-854--ethereumorg.netlify.com/dapps/

Here's a screenshot as well:
![Image 2020-03-30 at 8 33 45 PM](https://user-images.githubusercontent.com/8097623/77984323-1afb7680-72c6-11ea-8222-b9adf502a734.png)

Thanks again!

**Comment by spalladino** [comment]
Hey Sam, that's perfect! Thanks so much for the mention, and we're happy to be contributing to ethereum.org with bits of content!

**Comment by frangio** [comment]
For anyone else who would like to use the content from this site: there is no blanket license but we are happy to discuss each individual case and will generally grant permission to use if you reach out.
