### ISSUE TITLE
Add reference to @openzeppelin/contracts-ethereum-package to contracts

### ISSUE THREAD

**Issue by abcoathup** [OpenZeppelin/docs.openzeppelin.com#16]
We should have a reference to @openzeppelin/contracts-ethereum-package in the contracts documentation, it is referenced in the OpenZeppelin SDK documentation.

https://docs.openzeppelin.com/sdk/2.5/linking
> NOTE: Make sure you install @openzeppelin/contracts-ethereum-package and not the vanilla @openzeppelin/contracts. The latter is set up for general usage, while @openzeppelin/contracts-ethereum-package is tailored for being used with the OpenZeppelin SDK. This means that its contracts are already set up to be upgradeable.

So we could have something like this in the OpenZeppelin Contracts documentation at the install section https://docs.openzeppelin.com/contracts/2.x/#install: 

NOTE: If you are using OpenZeppelin SDK, make sure you use @openzeppelin/contracts-ethereum-package and not the vanilla @openzeppelin/contracts. The latter is set up for general usage, while @openzeppelin/contracts-ethereum-package is tailored for being used with the OpenZeppelin SDK. This means that its contracts are already set up to be upgradeable.  See [Linking OpenZeppelin contracts](https://docs.openzeppelin.com/sdk/2.5/linking) for how to use.

**Comment by abcoathup** [comment]
Based on feedback by PaulRBerg on the community Telegram.

**Comment by frangio** [comment]
Fixed in https://github.com/OpenZeppelin/openzeppelin-contracts/pull/2403.
