### ISSUE TITLE
Update Learn guides to use `oz deploy`

### ISSUE THREAD

**Issue by abcoathup** [OpenZeppelin/docs.openzeppelin.com#215]
Update Learn guides to use `oz deploy` rather than `oz create` which has been deprecated.

The following guides need to be updated:
https://docs.openzeppelin.com/learn/deploying-and-interacting#deploying-a-smart-contract
https://docs.openzeppelin.com/learn/connecting-to-public-test-networks#working-on-testnet
https://docs.openzeppelin.com/learn/upgrading-smart-contracts#upgrading-a-contract-via-cli

Reported in the community forum: https://forum.openzeppelin.com/t/create-deploying-upgradable-contract-error/2876

**Comment by frangio** [comment]
Learn guides no longer use OpenZeppelin CLI so this issue isn't relevant.
