### ISSUE TITLE
GSN example uses the wrong base contract name

### ISSUE THREAD

**Issue by vrde** [OpenZeppelin/docs.openzeppelin.com#231]
In the docs under [environment setup](https://docs.openzeppelin.com/learn/sending-gasless-transactions#environment-set-up) you require to install `@openzeppelin/contracts-ethereum-package`, later on in [creating our contract](https://docs.openzeppelin.com/learn/sending-gasless-transactions#creating-our-contract) the example contract is:

```
// contracts/Counter.sol
pragma solidity ^0.5.0;

import "@openzeppelin/contracts-ethereum-package/contracts/GSN/GSNRecipient.sol";

contract Counter is GSNRecipient {
    uint256 public value;
the contract is:
```

But the `GSNRecipient` abstract contract doesn't exist in `@openzeppelin/contracts-ethereum-package/contracts/GSN/GSNRecipient.sol"`, but in `openzeppelin-contracts/contracts/GSN/GSNRecipient.sol`.

In `@openzeppelin/contracts-ethereum-package/contracts/GSN/GSNRecipient.sol"` the abstract contact is called `GSNRecipientUpgradeSafe`.

**Comment by frangio** [comment]
Thanks @vrde, I've opened #232.

**Comment by frangio** [comment]
I hadn't realized this article is no longer featured in the site (only available through search) since our GSNv1 offering [entered maintenance only mode](https://forum.openzeppelin.com/t/doubling-down-on-security/2712).
