### ISSUE TITLE
Is the "Building a GSN-powered DApp" section obsolete?

### ISSUE THREAD

**Issue by vrde** [OpenZeppelin/docs.openzeppelin.com#233]
Related to https://github.com/OpenZeppelin/docs.openzeppelin.com/issues/231#issuecomment-642082483.

I've noticed that [Bulding a GSN-powered DApp](https://docs.openzeppelin.com/learn/sending-gasless-transactions#building-a-gsn-dapp) links to projects that are in maintenance mode, and AFAIK the development moved to OpenGSN. Would it make sense to remove the section "Bulding a GSN-powered DApp" from your docs, or point to the OpenGSN website?

**Comment by frangio** [comment]
We've removed all internal links to this page, but kept the page itself up to avoid breaking any links to it from the rest of the web.

But I agree that this is causing problems given that the page is no longer maintained. We should add a banner like the one we've added to the tools we no longer actively develop.
