### ISSUE TITLE
There seems to be a broken link on the CLI/Getting started page

### ISSUE THREAD

**Issue by anegg0** [OpenZeppelin/docs.openzeppelin.com#236]
The  [Getting Started page of OZ CLI](https://docs.openzeppelin.com/cli/2.8/getting-started#prerequisites) seems to have a [broken link](https://docs.openzeppelin.com/cli/2.8/getting-started#learn::setting-up-a-node-project):

 _________________________________________________________________________________

![image](https://user-images.githubusercontent.com/8999121/86821635-7f557100-c03f-11ea-9340-e7a7f83caa2c.png)

 _________________________________________________________________________________
The "TIP" paragraph offers deepers explanation on how to set up a node project but I was unable to find the content.
Happy to be redirected if I misunderstood.
__________________________________________________________________________________

After the facts: I found the content mentioned in the link [here](https://docs.openzeppelin.com/learn/setting-up-a-node-project)

**Comment by frangio** [comment]
Thank you for reporting! I've fixed the link in https://github.com/OpenZeppelin/openzeppelin-sdk/commit/3e2860ef7d5ea2d0397e0c5d25ed1d215d1e79f2.
