### ISSUE TITLE
Can't call initialize 

### ISSUE THREAD

**Issue by Mehranh** [OpenZeppelin/docs.openzeppelin.com#245]
Hi

I deployed my contract but when I called initialize method got this error:

 Choose the kind of deployment upgradeable
? Pick a network mainnet
? Pick a contract to deploy CrToken
√ Contract CrToken deployed
All implementations have been deployed
? Call a function to initialize the instance after creating it? Yes
? Select which function * initialize()
× Setting everything up to create contract instances
insufficient funds for gas * price + value

Now I can't call my methods again

I want to call initialize method without deploy again

I get this error 

oz call
? Pick a network mainnet
A contract address must be specified.

my code is:

```

pragma solidity ^0.6.0;


import '@openzeppelin/contracts-ethereum-package/contracts/Initializable.sol';
import '@openzeppelin/contracts-ethereum-package/contracts/presets/ERC20PresetMinterPauser.sol';
import '@openzeppelin/contracts-ethereum-package/contracts/access/Ownable.sol';
contract CrToken is Initializable, ERC20PresetMinterPauserUpgradeSafe   {

 uint256 private _totalSupply;


  function initialize() public initializer {
    ERC20PresetMinterPauserUpgradeSafe.initialize("Cryptomind", "CR");
      _setupDecimals(8);
	   _totalSupply = totalSupply();
	 
	   _mint(msg.sender, 2000000000 * (10 ** 8));
	  
  }


}
```

**Comment by frangio** [comment]
Closing this issue in favor of your forum post. https://forum.openzeppelin.com/t/i-couldnt-call-initialize-method/3840
