### ISSUE TITLE
can i open source my doc site which is based on docs.openzeppelin.com site?

### ISSUE THREAD

**Issue by sweepingmonk123** [OpenZeppelin/docs.openzeppelin.com#262]
Hello, before days , i developed my own help site with docs.openzeppelin.com project, all the theme is very alike (because i am not a programmer, so just revised some details, icons, links and others)
use this project on my own site is ok (at least i think), but can i put my own project open source ? is it ok ?

my doc site: https://insight.dtstack.com/public/helpSite/home/v1.0/home.html

**Comment by frangio** [comment]
Hi @sweepingmonk123!

I looked at your site (https://insight.dtstack.com/public/helpSite/home/v1.0/home.html) and I think it looks very different from our site. You changed the top bar, the typography, and the icons. (It looks very good!) This is all enough difference that we have no issue with you using the code. You can also freely publish the source code for the site in an open source repository.

Thank you for reaching out about it.

**Comment by sweepingmonk123** [comment]
> Hi @sweepingmonk123!
> 
> I looked at your site (https://insight.dtstack.com/public/helpSite/home/v1.0/home.html) and I think it looks very different from our site. You changed the top bar, the typography, and the icons. (It looks very good!) This is all enough difference that we have no issue with you using the code. You can also freely publish the source code for the site in an open source repository.
> 
> Thank you for reaching out about it.

thank you very much!!!
