### ISSUE TITLE
Maintain naming convention

### ISSUE THREAD

**Issue by navaru** [OpenZeppelin/docs.openzeppelin.com#272]
On page [learn/writing-automated-tests](https://docs.openzeppelin.com/learn/writing-automated-tests) in the first code example the test file is named `// test/Box.js` in other examples `// test/Box.test.js`.

> We will save the test as `test/Box.js.`

**Comment by frangio** [comment]
Thanks @navaru!

**Comment by navaru** [comment]
Oh, just noticed I could've edited that myself and open a PR, though an external CMS was used. Next time ☺️

**Comment by frangio** [comment]
@navaru Yeah, some of the content is on this repository. The project-specific content, like the docs for OpenZeppelin Contracts, are in each project repo.
