### ISSUE TITLE
Too many arguments given in erc777 _mint example

### ISSUE THREAD

**Issue by JonathanScialpi** [OpenZeppelin/docs.openzeppelin.com#277]
In the [ERC-777 guide](https://docs.openzeppelin.com/contracts/2.x/erc777),  the __mint_ function is called with one additional arguments (seems like msg.sender was used twice) where as the function is actually expecting only 4 arguments.

Example call in docs screenshot:
`_mint(msg.sender, msg.sender, initialSupply, "", "");`

ERC777.sol _mint function implementation:
`function _mint(
        address account,
        uint256 amount,
        bytes memory userData,
        bytes memory operatorData
    )
......`

The proper call should probably be this:
`_mint(msg.sender, initialSupply, "", "");`

**Comment by abcoathup** [comment]
Hi @JonathanScialpi,

In OpenZeppelin Contracts 2.x `_mint` had an operator parameter.
https://docs.openzeppelin.com/contracts/2.x/api/token/erc777#ERC777-_mint-address-address-uint256-bytes-bytes-

Whilst in OpenZeppelin Contracts 3.x this was removed.
https://docs.openzeppelin.com/contracts/3.x/api/token/erc777#ERC777-_mint-address-uint256-bytes-bytes-

The documentation you linked to is for OpenZeppelin Contracts 2.x
https://docs.openzeppelin.com/contracts/2.x/erc777#constructing_an_erc777_token_contract

The latest version of OpenZeppelin Contracts is 3.4 and the documentation matches the API.
https://docs.openzeppelin.com/contracts/3.x/erc777#constructing_an_erc777_token_contract

If you are using the current version of OpenZeppelin Contracts you should use the 3.x documentation (until OpenZeppelin Contracts 4 is released).

Let me know if I am missing something and we need to update the documentation?
