### ISSUE TITLE
Add Sepolia Testnet ETH faucet

### ISSUE THREAD

**Issue by anataliocs** [OpenZeppelin/docs.openzeppelin.com#348]
Infura just released a Sepolia Testnet Faucet that lets you claim 0.5 Sepolia ETH per day, for free. It's super easy to use, just visit [[infura.io/faucet](http://infura.io/faucet)](http://infura.io/faucet](http://infura.io/faucet)).

Sepolia Testnet is an important tool for testing your smart contracts before deploying them on mainnet environments. With our Testnet Faucet, you can easily catch bugs and reduce the cost of deploying tests on mainnet.

At Infura, we're all about making Web3 development easy and reliable. That's why we're excited to offer this important tool to help you achieve your goals.

**Comment by frangio** [comment]
Fixed in #349.
