### ISSUE TITLE
Style links in documentation generated from contracts natspec

### ISSUE THREAD

**Issue by spalladino** [OpenZeppelin/docs.openzeppelin.com#50]
Autogenerated docs from contracts natspec show links in plain text. They should be formatted as actual links. Check out what is the standard way for writing links in natspec (markdown? html? a custom notation?) and process it when generating the docs.

![image (1)](https://user-images.githubusercontent.com/429604/58422518-214b1180-8069-11e9-84da-bc465a9aef7a.png)

(reported by @ylv-io)

**Comment by frangio** [comment]
Note this particular example is not found in the site currently because of #54.

**Comment by frangio** [comment]
This was fixed by using AsciiDoc.
