### ISSUE TITLE
Add prerequisites section in documentation

### ISSUE THREAD

**Issue by spalladino** [OpenZeppelin/docs.openzeppelin.com#53]
We should add a section on prerequisites for different platforms, both for the CLI and ZepKit.

**Comment by nventuro** [comment]
Hm, this went under my radar. In the end our [setting-up](https://docs.openzeppelin.com/learn/setting-up-a-node-project) guide only covers a new Node project, and doesn't go into detail about the command-line or React.

I think this is fine, though we should add a note for Windows users (https://github.com/OpenZeppelin/docs.openzeppelin.com/issues/119).
