### ISSUE TITLE
Add syntax highlighting for diff blocks

### ISSUE THREAD

**Issue by nventuro** [OpenZeppelin/docs.openzeppelin.com#59]
Blocks marked as diff (using `[source,diff]`) don't get proper styles.

**Comment by frangio** [comment]
Note that we don't need to add custom CSS but find the proper plugin for our syntax highlighting thing. ~I don't remember which one we're using.~ highlight.js

**Comment by frangio** [comment]
We need to change this file: https://github.com/OpenZeppelin/docs.openzeppelin.com/blob/master/ui/src/scripts/vendor/highlight.js

Can you submit a PR please?

---

Somewhat related, in the highlight.js issues there's an idea for applying _both_ diff highlighting and a language's highlighting: https://github.com/highlightjs/highlight.js/issues/480#issuecomment-57007817. We might want to evaluate this later.
