### ISSUE TITLE
Collapse doesn't work on items that are pages themselves

### ISSUE THREAD

**Issue by nventuro** [OpenZeppelin/docs.openzeppelin.com#99]
When an item on the navbar is a link to a page, clicking on both the label and the arrow causes the site to navigate to the page. I'd expect the arrow to collapse instead.

So this navbar has no issues
```
.List
 * xref:page.adoc[Item A]
 * xref:other_page.adoc[Item B]
```

But this one does
```
.xref:about_pages.adoc[List]
 * xref:page.adoc[Item A]
 * xref:other_page.adoc[Item B]
```

**Comment by frangio** [comment]
Is this bug present in `full-site`? I believe we've fixed it in the new sidebar design.

**Comment by frangio** [comment]
This has been fixed.
